name: Test 25 # Related to https://stackoverflow.com/questions/71341486/github-action-assign-a-variable-of-type-env-an-array-of-strings

on:
  workflow_dispatch:

jobs:
  node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3 # Checkout the repository content to github runner.

      - name: Setup Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Install the node version needed
          
      - name: Setup
        id: summary
        uses: pl-strflt/job-summary-url-action@v1
        
      - name: set multiline env var
        run: |
          echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY
          echo 'URL<<EOF' >> $GITHUB_ENV
          cat $GITHUB_STEP_SUMMARY >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: use env var
        run: echo "${{ env.URL }}"

      - name: use env var directly
        run: echo "$URL"
        
      - name: Output run_id
        id: output_run_id
        shell: bash
        run: |
          echo '${{ steps.summary.outputs.job_summary_raw_url }}'
          echo "${{ env.URL }}"
          echo "This is summary: $GITHUB_STEP_SUMMARY"
          echo "$(cat $GITHUB_STEP_SUMMARY)"
      
        
